### ISSUE TITLE
PIL error but I have installed Pillow

### ISSUE THREAD

**Issue by somenormalguy7** [call-042PE/FuckVanguard#4]
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    import PIL.ImageGrab
ModuleNotFoundError: No module named 'PIL'

**Comment by call-042PE** [comment]
https://stackoverflow.com/questions/8863917/importerror-no-module-named-pil

**Comment by somenormalguy7** [comment]
Ok everything is perfect except aim assist

Exception in thread Thread-3:
Traceback (most recent call last):
File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "C:\Python38\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "test.py", line 79, in aimassist
c = interception()
File "C:\Users\Shamanth\Desktop\Vanguard-main\interception.py", line 28, in __init__
raise e
File "C:\Users\Shamanth\Desktop\Vanguard-main\interception.py", line 19, in __init__
_device = device(k32.CreateFileA(b'\\\\.\\interception%02d' % i,
File "C:\Users\Shamanth\Desktop\Vanguard-main\interception.py", line 114, in __init__
raise Exception("Can't create device")
Exception: Can't create device
Have a great day !


What to do?

**Comment by call-042PE** [comment]
Install interception driver

**Comment by somenormalguy7** [comment]
> Install interception driver

how to install?

**Comment by somenormalguy7** [comment]
> Install interception driver

Ok Done now no error
but what exactly aim assist do? I feel no change...how to use it

**Comment by call-042PE** [comment]
yeah don't use it, i will try to make a better one

**Comment by somenormalguy7** [comment]
> yeah don't use it, i will try to make a better one

Thank you 
Closing now
